import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { cn } from '@/utils'
import { UIProvider, Web3Provider, wagmiConfig } from '@/providers'
import { cookieToInitialState } from 'wagmi'
import { headers } from 'next/headers'
import { Footer } from '@/components/layout'

const comicSans = localFont({
  src: '../assets/fonts/ComicSansMS3.ttf',
  variable: '--font-comic-sans',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Devpass',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie'),
  )

  return (
    <html lang="en">
      <body
        className={cn(
          comicSans.variable,
          inter.variable,
          'bg-co-bg-1 font-sans',
        )}
      >
        <Web3Provider initialState={initialState}>
          <UIProvider>
            <div className="flex min-h-[100svh] w-full flex-col">
              <main className="h-full w-full flex-1">{children}</main>
              <Footer />
            </div>
          </UIProvider>
        </Web3Provider>
      </body>
    </html>
  )
}
